name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Latest version

      - name: Generate Snake Animation
        uses: Platane/snk@master  # Updated version
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Check if Snake SVG exists
        run: ls -l dist/

      - name: Upload the Snake Animation
        uses: actions/upload-artifact@v4  # Latest version
        with:
          name: snake
          path: dist/snake.svg

      - name: Setup GitHub Credentials
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Push Snake Animation to the repository
        run: |
          git pull origin main --rebase  # Ensure the branch is up to date
          git add dist/snake.svg
          git commit -m "Generated snake animation"
          git push --force

